const LOAD_PRODUCTS_REQUEST = "products:LOAD_PRODUCTS_REQUEST";
const LOAD_PRODUCTS_SUCCESS = "products:LOAD_PRODUCTS_SUCCESS";
const LOAD_PRODUCTS_FAILURE = "products:LOAD_PRODUCTS_FAILURE";

export default {
  LOAD_PRODUCTS_REQUEST,
  LOAD_PRODUCTS_SUCCESS,
  LOAD_PRODUCTS_FAILURE,
};
